"""Add template_id to WorkOrder

Revision ID: 91abc591ed5d
Revises: 
Create Date: 2025-06-02 13:09:05.678179

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '91abc591ed5d'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('work_orders', schema=None) as batch_op:
        batch_op.add_column(sa.Column('template_id', sa.Integer(), nullable=True))
        batch_op.create_foreign_key('fk_work_order_template', 'documents', ['template_id'], ['id'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('work_orders', schema=None) as batch_op:
        batch_op.drop_constraint('fk_work_order_template', type_='foreignkey')
        batch_op.drop_column('template_id')

    # ### end Alembic commands ###
